### ISSUE TITLE
Hey :)

### ISSUE THREAD

**Issue by Animenosekai** [Decimation/Lexgen#1]
https://github.com/Decimation/Lexgen/blob/42c0f9b3513d8c4972bd5b12372301bfead3a02b/Lexgen/Program.cs#L105

I just saw that you were using translatepy by calling `python -c` but just wanted to let you know that you could use it directly from the terminal, with a JSON formatted response: [Animenosekai/translate#in-other-applicationsfrom-the-terminal](https://github.com/Animenosekai/translate#in-other-applicationsfrom-the-terminal)

```bash
$ translatepy translate --dest-lang Français --text Hello
{
    "success": true,
    "service": "Google",
    "source": "Hello",
    "sourceLanguage": "eng",
    "destinationLanguage": "fra",
    "result": "Bonjour"
}
```

**Comment by Decimation** [comment]
Thanks for letting me know! I've updated the code accordingly.
